### ISSUE TITLE
Provide revisions of used libraries

### ISSUE THREAD

**Issue by krt16s** [enricocid/lffl-feed-reader#1]
I try to package this app for f-droid.org, a free/libre/open-source app "store". However I am struggeling with the used libraries. Could you point me to the used revisions/versions?

**Comment by krt16s** [comment]
I finally have a working build ready, I used:

Crouton@1.8.1
FadingActionBar@parent-3.0.0
LazyList@be926df2ec5ff81693251629748ed38655075393
JSoup@jsoup-1.8.1.a

**Comment by krt16s** [comment]
Could you comment more on FadingActionBar? Do you use the default/standard actionbar build or the one for the ActionBarSherlock? As I can't use any idea, I don't have any automagic import :/

**Comment by enricocid** [comment]
the standard build (in eclipse I import the one called "library")...
the others are extras or samples

**Comment by krt16s** [comment]
I cna't seem to get it right, could you just include your ../fadingactionbar or put it in another repo, so i can figure out what's wrong?

**Comment by enricocid** [comment]
what kind of problems do you have?
imports not resolved...
crashes?
the only things I change in fadingactionbar library (because of Eclipse errors) is
 android:targetSdkVersion="19" to android:targetSdkVersion="21" in manifest

**Comment by krt16s** [comment]
Hey, sorry for all the noise. I did tried to build without fdroid and got it to work, so nothing wrong on your side. In the end it was an unwanted `android update` in the background that was removing changes I was making in the build. Sigh. Again, sorry for the noise.

**Comment by enricocid** [comment]
Don't worry 😀
