### ISSUE TITLE
Increase android:versioncode

### ISSUE THREAD

**Issue by krt16s** [enricocid/lffl-feed-reader#2]
While you are tagging new releases, for Android all your version are the same. Look at the AndroidManifest.xml:

````
android:versionCode="1"
android:versionName="1.0"
````

The versionCode is an integer that should get increased on every release. It is used to compare APKs from the same app/package-id and decide which is the recent one. The versionName is just a fancy string, e.g. a codename or a humanreadble version string like "1.9".

**Comment by enricocid** [comment]
You're right, sorry for inconvenience, I'm so heedless . Thanks :)
