### ISSUE TITLE
Keeps on crashing on startup

### ISSUE THREAD

**Issue by deavmi** [enricocid/lffl-feed-reader#3]
Wheever I launch the app it keeps on crashing and exiting.

**Comment by enricocid** [comment]
I've downloaded the project and imported on eclipse, and it works
I need a logcat to help You

but I'm pretty sure that the problem is due to json library 

From Java build path: 
import it as an external .jar and then on "Import and Export" tab tickmark jsoup-1.8.1.jar

**Comment by deavmi** [comment]
I do not have root.

**Comment by enricocid** [comment]
if You're using eclipse navigate to 

Window --> Show View --> Other... --> Android --> Logcat --> OK

**Comment by deavmi** [comment]
I don't have an IDE for Android, I am running opn a hardware device. Not a
software emulator.

On Mon, Jan 5, 2015 at 12:32 PM, EnricoD <notifications@github.com> wrote:

> if You're using eclipse navigate to
>
> Window --> Show View --> Other... --> Android --> Logcat --> OK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enricocid/lffl-feed-reader/issues/3#issuecomment-68691155>
> .
>



-- 
Tristan K

**Comment by enricocid** [comment]
- Enable adb debug option
- Connect Your phone
- Open a terminal inside platform tools (sdk)
- Reproduce the error
- type
adb logcat -v long > lffl_prblem_name.txt
