### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by cycojesus** [enricocid/lffl-feed-reader#6]
The Following test is contradictory :
"""

    This work is 100% Free and is released under gpl license.

    RESPECT THE LICENSE!

    DO NOT REDISTRIBUTE THIS FOR SALE!

    ABSOLUTELY DO NOT REMOVE CREDITS!
"""

the last 2 points go against the GPL.

**Comment by enricocid** [comment]
the last 2 points are instructions not directly related to license 
i just don't want people to redistribuite it for sale

also, every derivative works must maintain due credits

**Comment by jimlee2** [comment]
@enricocid @cycojesus well technically if someone use your project, then they also have to make their own project GPL.
Also please [read this](http://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary) : 
>I'd like to license my code under the GPL, but I'd also like to make it clear that it can't be used for military and/or commercial uses. Can I do this?

>No, because those two goals contradict each other. The GNU GPL is designed specifically to prevent the addition of further restrictions. GPLv3 allows a very limited set of them, in section 7, but any other added restriction can be removed by the user.

I think you need to pick a new license not the GPL if you have those restrictions

**Comment by enricocid** [comment]
readme fixed :) thank You all :)
