### ISSUE TITLE
a problem with domperser

### ISSUE THREAD

**Issue by nemati456** [enricocid/lffl-feed-reader#7]
hi 
i found A  new bug with class "domperser"
in this loop must start j=0 not j=1
for (int j = 0; j < clength; j ++) {
....}
because not grab first element in feed
e.g
http://www.feedforall.com/sample.xml

just grab:
link
pubDate
description
category
comments

and title not grab because j=1 and not j=0

thanks  for your great project 
i have a new idea that is add some more feature for grab for  rss feed 

thanks a lot and sorry for my poor english

**Comment by enricocid** [comment]
thank You
You're right
I would like You send me a pull request with this correction
thank You again:)

**Comment by nemati456** [comment]
we are waiting for your great project to add more feature thanks again
